Entrega1+de+la+Quintana/Entrega_Intermedia/bank/urls.py
from django.urls import path

from student import views

app_name = "student"
urlpatterns = [
    path("banks", views.BankListView.as_view(), name="bank-list"),
    path("bank/add/", views.BankCreateView.as_view(), name="bank-add"),
    path("bank/<int:pk>/detail/", views.BankDetailView.as_view(), name="bank-detail"),
    path("bank/<int:pk>/update/", views.BankUpdateView.as_view(), name="bank-update"),
    path("bank/<int:pk>/delete/", views.BankDeleteView.as_view(), name="bank-delete"),
]

Entrega1+de+la+Quintana/Entrega_Intermedia/my_app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("bank/", include("bank.urls")),
    path("creeditcard/", include("creditcard.urls")),
    path("person/", include("person.urls")),
]

Entrega1+de+la+Quintana/Entrega_Intermedia/person/urls.py
from django.urls import path

from person import views

app_name = "person"
urlpatterns = [
    path("persons", views.personListView.as_view(), name="person-list"),
    path("person/add/", views.PersonCreateView.as_view(), name="person-add"),
    path("person/<int:pk>/detail/", views.PersonDetailView.as_view(), name="person-detail"),
    path("person/<int:pk>/update/", views.PersonUpdateView.as_view(), name="person-update"),
    path("person/<int:pk>/delete/", views.PersonDeleteView.as_view(), name="person-delete"),
]

Entrega1+de+la+Quintana/Entrega_Intermedia/person/models.py
from django.db import models


class Person(models.Model):
    name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    birth_date = models.DateField(max_length=40)

    def __str__(self):
        return f"{self.name} {self.last_name}"

Entrega1+de+la+Quintana/Entrega_Intermedia/person/forms.py
from django import forms

from profesor.models import Profesor

class PersonForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre del titular",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "person-name",
                "placeholder": "Nombre del titular",
                "required": "True",
            }
        ),
    )
    last_name = forms.CharField(
        label="Apellido del titular",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "person-last-name",
                "placeholder": "Apellido del titular",
                "required": "True",
            }
        ),
    )
    email = forms.EmailField(
        label="Email:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "person-email",
                "placeholder": "Email",
                "required": "True",
            }
        ),
    )
    birth_date = forms.DateInput()(
        label="Fecha de nacimiento:",
        max_length=20,
        required=False,
        widget=forms.NumberInput(
            attrs={
                "class": "person-birth-date",
                "placeholder": "Fecha de nacimiento",
                "required": "True",
            }
        ),
    )

    class Meta:
        model = Person
        fields = ["name", "last_name", "email", "birth_date"]

Entrega1+de+la+Quintana/Entrega_Intermedia/person/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from profesor.models import Person
from person.forms import PersonForm


class PersonListView(ListView):
    model = Person
    paginate_by = 3


class PersonDetailView(DetailView):
    model = Person
    fields = ["name", "last_name", "email", "birth_date"]


class PersonCreateView(LoginRequiredMixin, CreateView):
    model = Person
    success_url = reverse_lazy("person:person-list")

    form_class = PersonForm

    def form_valid(self, form):
        """Filter to avoid duplicate persons"""
        data = form.cleaned_data
        actual_objects = Person.objects.filter(
            name=data["name"],
            last_name=data["last_name"],
            email=data["email"],
            birth_date=["birth_date"]
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"La persona {data['name']} {data['last_name']} | {data['email']} | {data['birth_date']} ya está creado",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Person: {data['name']} - {data['last_name']}. Creado exitosamente!",
            )
            return super().form_valid(form)


class PersonUpdateView(LoginRequiredMixin, UpdateView):
    model = Person
    fields = ["name", "last_name", "email", "birth_date"]

    def get_success_url(self):
        person_id = self.kwargs["pk"]
        return reverse_lazy("person:person-detail", kwargs={"pk": person_id})


class PersonDeleteView(LoginRequiredMixin, DeleteView):
    model = Person
    success_url = reverse_lazy("person:person-list")

Entrega1+de+la+Quintana/Entrega_Intermedia/person/templates/profesor/person_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_app_title %}
person delete
{% endblock %}

{% block my_app_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ person.name }}</h1>
                    <span class="subheading">Eliminar Persona</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar a la persona: {{ person.name }} {{ person.last_name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'person:person-list' %}" >Cancelar</a>
</form>

{% endblock %}

Entrega1+de+la+Quintana/Entrega_Intermedia/person/templates/profesor/person_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_app_title %}
Person details
{% endblock %}

{% block my_app_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ person.name }} {{ person.last_name }}</h1>
                    <span class="subheading">Detalles de la persona</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'persona:persona-add' %}">Crear nueva persona</a>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Email: {{ person.email }}</h3>
    <h3 class="post-subtitle">Profesión: {{ person.birth_date }}</h3>
    <p style="text-align: center">
        <a href="{% url 'person:person-update' person.id %}">
            <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar
        </a>
        &ensp; | &ensp;
        <a href="{% url 'person:person-delete' person.id %}">
            <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar 
        </a>
    </p>
</div>
{% endblock %}

Entrega1+de+la+Quintana/Entrega_Intermedia/person/templates/profesor/person_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_app_title %}
Person Create-Update
{% endblock %}

{% block my_app_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar una persona</h2>
                    <span class="subheading">Entrega intermedia de la Quintana</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_app_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar persona" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

Entrega1+de+la+Quintana/Entrega_Intermedia/person/templates/profesor/person_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_app_title %}
Profesor
{% endblock %}

{% block my_app_header %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Listado de personas</h1>
                        <span class="subheading">Entrega intermedia de la Quintana</span>
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'person:person-add' %}">Crear nueva persona</a>
        </div>
    </header>
{% endblock %}

{% block my_app_content %}
    {% for person in person_list %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'person:person-detail' person.id %}">
                <h2 class="post-title">Nombre: {{ person.name }}  {{ person.last_name }}</h2>
                <h3 class="post-subtitle">Email: {{ person.email }}</h3>
                <h3 class="post-subtitle">Fecha de nacimiento: {{ person.birth_date }}</h3>
            </a>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}