Entrega1+de+la+Quintana/Entrega_Intermedia/bank/urls.py
from django.urls import path

from student import views

app_name = "student"
urlpatterns = [
    path("banks", views.BankListView.as_view(), name="bank-list"),
    path("bank/add/", views.BankCreateView.as_view(), name="bank-add"),
    path("bank/<int:pk>/detail/", views.BankDetailView.as_view(), name="bank-detail"),
    path("bank/<int:pk>/update/", views.BankUpdateView.as_view(), name="bank-update"),
    path("bank/<int:pk>/delete/", views.BankDeleteView.as_view(), name="bank-delete"),
]

Entrega1+de+la+Quintana/Entrega_Intermedia/creditcard/urls.py
from django.urls import path

from creditcard import views

app_name = "creditcard"
urlpatterns = [
    path("creditcard/", views.creditcardListView.as_view(), name="creditcard-list"),
    path("creditcard/add/", views.creditcardCreateView.as_view(), name="creditcard-add"),
    path("creditcard/<int:pk>/detail/", views.creditcardDetailView.as_view(), name="creditcard-detail"),
    path("creditcard/<int:pk>/update/", views.creditcardUpdateView.as_view(), name="creditcard-update"),
    path("creditcard/<int:pk>/delete/", views.creditcardDeleteView.as_view(), name="creditcard-delete"),
]

Entrega1+de+la+Quintana/Entrega_Intermedia/my_app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("bank/", include("bank.urls")),
    path("creeditcard/", include("creditcard.urls")),
    path("person/", include("person.urls")),
]

Entrega1+de+la+Quintana/Entrega_Intermedia/creditcard/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from ckeditor.fields import RichTextField


class CreditCard(models.Model):
    name = models.CharField(max_length=40, null=False, blank=False)
    code = models.IntegerField(null=False, blank=False)
    expire_date = RichTextField(null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            "name",
            "code",
            "expire_date"
        )
        ordering = ["-created_at"]

    def __str__(self):
        return f"Credit Card: {self.name} | code: {self.code} | expire_date: {self.expire_date}"

Entrega1+de+la+Quintana/Entrega_Intermedia/creditcard/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from creditcard.models import CreditCard


class CreditCardForm(forms.ModelForm):
    name = forms.CharField(
        label="Titular de la Tarjeta",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "creditcard-name",
                "placeholder": "Nombre del titular",
                "required": "True",
            }
        ),
    )

    code = forms.IntegerField(
        label="Código:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "creditcard-code",
                "placeholder": "Credit Card Code",
                "required": "True",
            }
        ),
    )
    expire_date = forms.IntegerField(
        label="Fecha de Expiracion:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "creditcard-exp-date",
                "placeholder": "Credit Card Expiration Date",
                "required": "True",
            }
        ),
    )


    class Meta:
        model = Course
        fields = ["name", "code", "expire-date"]

Entrega1+de+la+Quintana/Entrega_Intermedia/creditcard/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from creditcard.forms import CommentForm
from creditcard.forms import CreditCardForm
from creditcard.models import CreditCard


class CreditCardListView(ListView):
    model = creditcard
    paginate_by = 3


class CreditCardDetailView(DetailView):
    model = CreditCard
    template_name = "creditcard/creditcard_detail.html"
    fields = ["name", "code", "description"]

    def get(self, request, pk):
        creditcard = creditcard.objects.get(id=pk)
        comments = Comment.objects.filter(creditcard=creditcard).order_by("-updated_at")
        comment_form = CommentForm()
        context = {
            "creditcard": creditcard,
            "comments": comments,
            "comment_form": comment_form,
        }
        return render(request, self.template_name, context)


class CreditCardCreateView(LoginRequiredMixin, CreateView):
    model = CreditCard
    success_url = reverse_lazy("creditcard:creditcard-list")

    form_class = CreditCardForm
    
    def form_valid(self, form):
        """Filter to avoid duplicate creditcards"""
        data = form.cleaned_data
        form.instance.owner = self.request.user
        actual_objects = CreditCard.objects.filter(
            name=data["name"], code=data["code"], expire_date=data["expire_date"],
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"La Tarjeta de credito {data['name']} - {data['code']} - {data['expire_date']} ya está en la base de datos",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"La tarjeta de credito {data['name']} - {data['code']} a sido subida exitosamente!",
            )
            return super().form_valid(form)


class CreditCardUpdateView(LoginRequiredMixin, UpdateView):
    model = CreditCard
    fields = ["name", "code", "description"]

    def get_success_url(self):
        creditcard_id = self.kwargs["pk"]
        return reverse_lazy("creditcard:creditcard-detail", kwargs={"pk": creditcard_id})


class CreditCardDeleteView(LoginRequiredMixin, DeleteView):
    model = CreditCard
    success_url = reverse_lazy("creditcard:creditcard-list")

Entrega1+de+la+Quintana/Entrega_Intermedia/creditcard/templates/course/creditcard_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_app_title %}
Credit Card delete
{% endblock %}

{% block my_app_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ creditcard.name }}</h1>
                    <span class="subheading">Eliminar tarjeta de credito</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_app_content %}

<h1>Estás seguro de eliminar la tarjeta de credito: {{ creditcard.name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'creditcard:creditcard-list' %}" >Cancelar</a>
</form>

{% endblock %}

Entrega1+de+la+Quintana/Entrega_Intermedia/creditcard/templates/course/creditcard_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_app_title %}
Creditcard detail
{% endblock %}

{% block my_app_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ creditcard.name }}</h1>
                    <span class="subheading">Detalles del curso</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'creditcard:creditcard-add' %}">Crear nuevo Curso</a>
    </div>
</header>
{% endblock %}


{% block my_app_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Código: {{ creditcard.code }}</h3>
    <p class="post-meta">
        Creado por
        <span style="color: #0b4956;" href="">{{ creditcard.owner.username }}</span>
        ( {{ creditcard.created_at }} )
        <br>
        Última fecha de actualización ( {{ creditcard.updated_at }} )
    </p>
    <p class="card-text ">{{ creditcard.description|safe }}</p> <!-- ckeditor-->

    <!-- Update-Delete link only for the owner -->
    {% if user == creditcard.owner or user.is_superuser %}
        <p style="text-align: center">
            <a href="{% url 'creditcard:creditcard-update' creditcard.id %}">
                <i class="fa fa-pencil" style="color: #1c1c91;"></i> Editar Curso
            </a>
            &ensp; | &ensp;
            <a href="{% url 'creditcard:creditcard-delete' creditcard.id %}">
                <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar Curso
            </a>
        </p>
    {% endif %}
    
    <!-- Divider-->
    <hr class="my-4" />

    <!-- Comment creation -->
    <form method="post" action="{% url 'creditcard:comment-create' creditcard.id %}">
        {% csrf_token %}
        {{ comment_form }}
    <input type="submit" value="Publicar comentario">
    </form>
    {% if not comments %}
        <p></p>
    {% endif %}

    <!-- Comments list -->
    {% for comment in comments %}
        <p> {{ comment.text }}
            ({{ comment.owner.username }} | {{ comment.updated_at }})
            {% if user == comment.owner or user.is_superuser %}
            <a href="{% url 'creditcard:comment-delete' comment.id %}"><i class="fa fa-trash" style="color: #881a1a;"></i></a>
            {% endif %}
        </p>
    {% endfor %}
</div>
{% endblock %}

Entrega1+de+la+Quintana/Entrega_Intermedia/creditcard/templates/course/creditcard_form.html
{% extends "home/index.html" %}
{% load static %}

<!-- ckeditor-->
{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
<!-- ckeditor-->

{% block my_blog_title %}
Course Create-Update
{% endblock %}

{% block my_app_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar tarjeta de credito</h2>
                    <span class="subheading">Entrega intermedia de la Quintana</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_app_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.media }} <!-- ckeditor-->
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar tarjeta" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

Entrega1+de+la+Quintana/Entrega_Intermedia/creditcard/templates/course/creditcard_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_app_title %}
Credit cards list
{% endblock %}

{% block my_app_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Listado de tarjetas de credito</h1>
                    <span class="subheading">Entrega intermedia de la Quintana</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'creditcard:creditcard-add' %}">Crear nueva tarjeta</a>
    </div>
</header>
{% endblock %}


{% block my_app_content %}
    {% for creditcard in creditcard_list %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'creditcard:creditcard-detail' creditcard.id %}">
                <h2 class="post-title">Este es el curso de {{ creditcard.name }}</h2>
                <h3 class="post-subtitle">Que tiene el código: {{ creditcard.code }}</h3>
            </a>
            <p class="post-meta">
                Creado por
                <span style="color: #0b4956;" href="">{{ creditcard.owner.username }}</span>
                ( {{ creditcard.created_at }} )
            </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}